### ISSUE TITLE
connection failed: gatt status 133 BT mode

### ISSUE THREAD

**Issue by JLFra** [dev-fred/Decode_balise_ESP32#1]
Hello,

I try your BLE mode.
But when I use the serial bleutooth application on android 10. I have a error when connect to the decode_balise?
connection failed: gatt status 133 BT mode
So I can't connect to the BLE of my ESP32 receiver.
My balise is ok I can read on the terminal serial on arduino the beacon trame.
thanks to help.
regards.

Julien

**Comment by JLFra** [comment]
Ok it's working. But in classic mode, not in BLE mode.
JL

**Comment by JLFra** [comment]
I have done the same application in BLE mode, and I create a apk to read the data and see the point on a map. Julien

**Comment by dev-fred** [comment]
I am interested by your code ;<)
