### ISSUE TITLE
issue in decode balise Heading

### ISSUE THREAD

**Issue by JLFra** [dev-fred/Decode_balise_ESP32#2]
Hello,

There is an issue in decode balise.
Your wrote 1,  // [DATA_TYPE::HEADING] So we read heading DIR=0 or DIR=1 only because we have to read 2 bytes and not 1 byte in the protocol.
But it's 2 bytes, not 1 bytes
so the wright correction is
2,  // [DATA_TYPE::HEADING]

And then DIR will print the right heading, thanks to make a correction.
Regards.

Julien

**Comment by dev-fred** [comment]
Thx
