### ISSUE TITLE
Manque bibliothèque Button2 dans readme

### ISSUE THREAD

**Issue by PascalRZ** [dev-fred/Decode_balise_ESP32#3]
Bonsoir et félicitations pour votre travail.
Je profite de nos obligations d'avoir des balises dans nos modèles pour m'essayer à l'Arduino. J'ai voulu installer le Decode_balise_ESP32 sur un TTGO. J'ai bien suivi vos instructions mais la compilation n'a pas marché. Il manquait la bibliothèque Button2 que l'on peut télécharger ici:
https://github.com/LennartHennigs/Button2

Pouvez-vous ajouter cette explication dans le readme pour les futurs utilisateurs de la balise ?

Cordialement.
PascalRZ

**Comment by FredsFactory** [comment]
Bonjour,
merci mais le code n’est pas de moi, il s’agit d’un fork du git suivant : forked from dev-fred/Decode_balise_ESP32 <https://github.com/dev-fred/Decode_balise_ESP32>
Je vous conseil de contacter l’auteur initial du projet.

Frédéric
